/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(500, 530);
        setResizable(false);
        setTitle(" Acceso al sistema");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registrarse = new javax.swing.JDialog();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        bt_registrado = new javax.swing.JButton();
        bt_regresar = new javax.swing.JButton();
        wallpaer = new javax.swing.JLabel();
        tf_passwordd = new javax.swing.JPasswordField();
        bt_ingresar = new javax.swing.JButton();
        bt_registrarse = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        tf_user = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        lb_fondo = new javax.swing.JLabel();

        jd_registrarse.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("jTextField2");
        jd_registrarse.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("jTextField2");
        jd_registrarse.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("jTextField2");
        jd_registrarse.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Contraseña");
        jd_registrarse.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Nombre");
        jd_registrarse.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, -1));

        bt_registrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registration.png"))); // NOI18N
        jd_registrarse.getContentPane().add(bt_registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 100, 40));

        bt_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/undo.png"))); // NOI18N
        bt_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_regresarMouseClicked(evt);
            }
        });
        jd_registrarse.getContentPane().add(bt_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 100, 40));

        wallpaer.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        wallpaer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallpaer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/note.png"))); // NOI18N
        jd_registrarse.getContentPane().add(wallpaer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 510, 640));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_passwordd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_passwordd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 210, 50));

        bt_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        getContentPane().add(bt_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 130, 50));

        bt_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registration.png"))); // NOI18N
        bt_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarseMouseClicked(evt);
            }
        });
        getContentPane().add(bt_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        bt_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_salirMouseClicked(evt);
            }
        });
        getContentPane().add(bt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, 50));

        tf_user.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        tf_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 210, 60));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Registrate");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login (1).png"))); // NOI18N
        getContentPane().add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bt_salirMouseClicked

    private void bt_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarseMouseClicked

        jd_registrarse.pack();
        jd_registrarse.setModal(true);
        jd_registrarse.setLocationRelativeTo(this);
        jd_registrarse.setVisible(true);

    }//GEN-LAST:event_bt_registrarseMouseClicked

    private void bt_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_regresarMouseClicked
       jd_registrarse.setVisible(false);
    }//GEN-LAST:event_bt_regresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_registrado;
    private javax.swing.JButton bt_registrarse;
    private javax.swing.JButton bt_regresar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JDialog jd_registrarse;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JPasswordField tf_passwordd;
    private javax.swing.JTextField tf_user;
    private javax.swing.JLabel wallpaer;
    // End of variables declaration//GEN-END:variables
}
